### ISSUE TITLE
Update Generator status sensor

### ISSUE THREAD

**Issue by rperciaccante** [rperciaccante/HomeAssistant_OneControl_Discovery#26]
Update generator sensor to accomodate new options:
```
link: >-
  http://192.168.1.4:8080/rest/items/idsmyrv_generator_thing_0000000DA7271800_state
state: 'OFF'
stateDescription:
  readOnly: true
  options:
    - value: 'OFF'
      label: 'Off'
    - value: PRIMING
      label: Priming
    - value: STARTING
      label: Starting
    - value: RUNNING
      label: Running
    - value: STOPPING
      label: Stopping
type: String
name: idsmyrv_generator_thing_0000000DA7271800_state
label: Device State
tags: []
groupNames: []
```
