### ISSUE TITLE
Update HVAC Status sensor

### ISSUE THREAD

**Issue by rperciaccante** [rperciaccante/HomeAssistant_OneControl_Discovery#27]
Make provisions for the following;
```
link: 'http://192.168.1.4:8080/rest/items/idsmyrv_hvac_thing_0000000DA7271001_status'
state: IDLE
stateDescription:
  readOnly: true
  options:
    - value: 'OFF'
      label: 'Off'
    - value: IDLE
      label: Idle
    - value: COOLING
      label: Cooling
    - value: HEAT_PUMP
      label: Heat Pump
    - value: ELEC_FURNACE
      label: Electric Furnace
    - value: GAS_FURNACE
      label: Gas Furnace
    - value: GAS_OVERRIDE
      label: Gas Override
    - value: DEAD_TIME
      label: Dead Time
    - value: LOAD_SHEDDING
      label: Load Shedding
    - value: FAIL_OFF
      label: FAIL OFF
    - value: FAIL_IDLE
      label: FAIL IDLE
    - value: FAIL_COOLING
      label: FAIL COOLING
    - value: FAIL_HEAT_PUMP
      label: FAIL HEAT PUMP
    - value: FAIL_ELEC_FURNACE
      label: FAIL ELECTRIC FURNACE
    - value: FAIL_GAS_FURNACE
      label: FAIL GAS FURNACE
    - value: FAIL_GAS_OVERRIDE
      label: FAIL GAS OVERRIDE
    - value: FAIL_DEAD_TIME
      label: FAIL DEAD TIME
    - value: FAIL_SHEDDING
      label: FAIL SHEDDING
type: String
name: idsmyrv_hvac_thing_0000000DA7271001_status
label: HVAC Status
tags: []
groupNames: []
```
